version: "3.7"
name: octolane-company-ai-analyze-app

services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    mem_limit: 1g
    ports:
      - 3100:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: octolane
      POSTGRES_USER: root
    volumes:
      - /var/lib/postgresql/octolane-company-ai-analyze/data:/var/lib/postgresql/data
